// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/Trade.proto
// Protobuf Java Version: 4.31.0

package com.semeniuk.lab3.protobuf;

@com.google.protobuf.Generated
public final class TradeOuterClass {
  private TradeOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      TradeOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TradeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trade)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stream = 1;</code>
     * @return The stream.
     */
    java.lang.String getStream();
    /**
     * <code>string stream = 1;</code>
     * @return The bytes for stream.
     */
    com.google.protobuf.ByteString
        getStreamBytes();

    /**
     * <code>string coin = 2;</code>
     * @return The coin.
     */
    java.lang.String getCoin();
    /**
     * <code>string coin = 2;</code>
     * @return The bytes for coin.
     */
    com.google.protobuf.ByteString
        getCoinBytes();

    /**
     * <code>string price = 3;</code>
     * @return The price.
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 3;</code>
     * @return The bytes for price.
     */
    com.google.protobuf.ByteString
        getPriceBytes();

    /**
     * <code>string quantity = 4;</code>
     * @return The quantity.
     */
    java.lang.String getQuantity();
    /**
     * <code>string quantity = 4;</code>
     * @return The bytes for quantity.
     */
    com.google.protobuf.ByteString
        getQuantityBytes();

    /**
     * <code>int64 tradeTime = 5;</code>
     * @return The tradeTime.
     */
    long getTradeTime();
  }
  /**
   * Protobuf type {@code Trade}
   */
  public static final class Trade extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Trade)
      TradeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        Trade.class.getName());
    }
    // Use Trade.newBuilder() to construct.
    private Trade(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Trade() {
      stream_ = "";
      coin_ = "";
      price_ = "";
      quantity_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.semeniuk.lab3.protobuf.TradeOuterClass.internal_static_Trade_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.semeniuk.lab3.protobuf.TradeOuterClass.internal_static_Trade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.semeniuk.lab3.protobuf.TradeOuterClass.Trade.class, com.semeniuk.lab3.protobuf.TradeOuterClass.Trade.Builder.class);
    }

    public static final int STREAM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stream_ = "";
    /**
     * <code>string stream = 1;</code>
     * @return The stream.
     */
    @java.lang.Override
    public java.lang.String getStream() {
      java.lang.Object ref = stream_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stream_ = s;
        return s;
      }
    }
    /**
     * <code>string stream = 1;</code>
     * @return The bytes for stream.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreamBytes() {
      java.lang.Object ref = stream_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stream_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COIN_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object coin_ = "";
    /**
     * <code>string coin = 2;</code>
     * @return The coin.
     */
    @java.lang.Override
    public java.lang.String getCoin() {
      java.lang.Object ref = coin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coin_ = s;
        return s;
      }
    }
    /**
     * <code>string coin = 2;</code>
     * @return The bytes for coin.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoinBytes() {
      java.lang.Object ref = coin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object price_ = "";
    /**
     * <code>string price = 3;</code>
     * @return The price.
     */
    @java.lang.Override
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 3;</code>
     * @return The bytes for price.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object quantity_ = "";
    /**
     * <code>string quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public java.lang.String getQuantity() {
      java.lang.Object ref = quantity_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quantity_ = s;
        return s;
      }
    }
    /**
     * <code>string quantity = 4;</code>
     * @return The bytes for quantity.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQuantityBytes() {
      java.lang.Object ref = quantity_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quantity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRADETIME_FIELD_NUMBER = 5;
    private long tradeTime_ = 0L;
    /**
     * <code>int64 tradeTime = 5;</code>
     * @return The tradeTime.
     */
    @java.lang.Override
    public long getTradeTime() {
      return tradeTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stream_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, stream_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(coin_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, coin_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, quantity_);
      }
      if (tradeTime_ != 0L) {
        output.writeInt64(5, tradeTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stream_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, stream_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(coin_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, coin_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, quantity_);
      }
      if (tradeTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, tradeTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.semeniuk.lab3.protobuf.TradeOuterClass.Trade)) {
        return super.equals(obj);
      }
      com.semeniuk.lab3.protobuf.TradeOuterClass.Trade other = (com.semeniuk.lab3.protobuf.TradeOuterClass.Trade) obj;

      if (!getStream()
          .equals(other.getStream())) return false;
      if (!getCoin()
          .equals(other.getCoin())) return false;
      if (!getPrice()
          .equals(other.getPrice())) return false;
      if (!getQuantity()
          .equals(other.getQuantity())) return false;
      if (getTradeTime()
          != other.getTradeTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREAM_FIELD_NUMBER;
      hash = (53 * hash) + getStream().hashCode();
      hash = (37 * hash) + COIN_FIELD_NUMBER;
      hash = (53 * hash) + getCoin().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity().hashCode();
      hash = (37 * hash) + TRADETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTradeTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.semeniuk.lab3.protobuf.TradeOuterClass.Trade prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trade}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trade)
        com.semeniuk.lab3.protobuf.TradeOuterClass.TradeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.semeniuk.lab3.protobuf.TradeOuterClass.internal_static_Trade_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.semeniuk.lab3.protobuf.TradeOuterClass.internal_static_Trade_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.semeniuk.lab3.protobuf.TradeOuterClass.Trade.class, com.semeniuk.lab3.protobuf.TradeOuterClass.Trade.Builder.class);
      }

      // Construct using com.semeniuk.lab3.protobuf.TradeOuterClass.Trade.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stream_ = "";
        coin_ = "";
        price_ = "";
        quantity_ = "";
        tradeTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.semeniuk.lab3.protobuf.TradeOuterClass.internal_static_Trade_descriptor;
      }

      @java.lang.Override
      public com.semeniuk.lab3.protobuf.TradeOuterClass.Trade getDefaultInstanceForType() {
        return com.semeniuk.lab3.protobuf.TradeOuterClass.Trade.getDefaultInstance();
      }

      @java.lang.Override
      public com.semeniuk.lab3.protobuf.TradeOuterClass.Trade build() {
        com.semeniuk.lab3.protobuf.TradeOuterClass.Trade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.semeniuk.lab3.protobuf.TradeOuterClass.Trade buildPartial() {
        com.semeniuk.lab3.protobuf.TradeOuterClass.Trade result = new com.semeniuk.lab3.protobuf.TradeOuterClass.Trade(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.semeniuk.lab3.protobuf.TradeOuterClass.Trade result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stream_ = stream_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.coin_ = coin_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.quantity_ = quantity_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.tradeTime_ = tradeTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.semeniuk.lab3.protobuf.TradeOuterClass.Trade) {
          return mergeFrom((com.semeniuk.lab3.protobuf.TradeOuterClass.Trade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.semeniuk.lab3.protobuf.TradeOuterClass.Trade other) {
        if (other == com.semeniuk.lab3.protobuf.TradeOuterClass.Trade.getDefaultInstance()) return this;
        if (!other.getStream().isEmpty()) {
          stream_ = other.stream_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCoin().isEmpty()) {
          coin_ = other.coin_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getQuantity().isEmpty()) {
          quantity_ = other.quantity_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getTradeTime() != 0L) {
          setTradeTime(other.getTradeTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                stream_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                coin_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                price_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                quantity_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                tradeTime_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object stream_ = "";
      /**
       * <code>string stream = 1;</code>
       * @return The stream.
       */
      public java.lang.String getStream() {
        java.lang.Object ref = stream_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stream_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stream = 1;</code>
       * @return The bytes for stream.
       */
      public com.google.protobuf.ByteString
          getStreamBytes() {
        java.lang.Object ref = stream_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stream_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stream = 1;</code>
       * @param value The stream to set.
       * @return This builder for chaining.
       */
      public Builder setStream(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stream_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string stream = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStream() {
        stream_ = getDefaultInstance().getStream();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string stream = 1;</code>
       * @param value The bytes for stream to set.
       * @return This builder for chaining.
       */
      public Builder setStreamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stream_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object coin_ = "";
      /**
       * <code>string coin = 2;</code>
       * @return The coin.
       */
      public java.lang.String getCoin() {
        java.lang.Object ref = coin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          coin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string coin = 2;</code>
       * @return The bytes for coin.
       */
      public com.google.protobuf.ByteString
          getCoinBytes() {
        java.lang.Object ref = coin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string coin = 2;</code>
       * @param value The coin to set.
       * @return This builder for chaining.
       */
      public Builder setCoin(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        coin_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string coin = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCoin() {
        coin_ = getDefaultInstance().getCoin();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string coin = 2;</code>
       * @param value The bytes for coin to set.
       * @return This builder for chaining.
       */
      public Builder setCoinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        coin_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 3;</code>
       * @return The price.
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 3;</code>
       * @return The bytes for price.
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 3;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        price_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        price_ = getDefaultInstance().getPrice();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string price = 3;</code>
       * @param value The bytes for price to set.
       * @return This builder for chaining.
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        price_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object quantity_ = "";
      /**
       * <code>string quantity = 4;</code>
       * @return The quantity.
       */
      public java.lang.String getQuantity() {
        java.lang.Object ref = quantity_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          quantity_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string quantity = 4;</code>
       * @return The bytes for quantity.
       */
      public com.google.protobuf.ByteString
          getQuantityBytes() {
        java.lang.Object ref = quantity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          quantity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string quantity = 4;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        quantity_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string quantity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        quantity_ = getDefaultInstance().getQuantity();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string quantity = 4;</code>
       * @param value The bytes for quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        quantity_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private long tradeTime_ ;
      /**
       * <code>int64 tradeTime = 5;</code>
       * @return The tradeTime.
       */
      @java.lang.Override
      public long getTradeTime() {
        return tradeTime_;
      }
      /**
       * <code>int64 tradeTime = 5;</code>
       * @param value The tradeTime to set.
       * @return This builder for chaining.
       */
      public Builder setTradeTime(long value) {

        tradeTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 tradeTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTradeTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tradeTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Trade)
    }

    // @@protoc_insertion_point(class_scope:Trade)
    private static final com.semeniuk.lab3.protobuf.TradeOuterClass.Trade DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.semeniuk.lab3.protobuf.TradeOuterClass.Trade();
    }

    public static com.semeniuk.lab3.protobuf.TradeOuterClass.Trade getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trade>
        PARSER = new com.google.protobuf.AbstractParser<Trade>() {
      @java.lang.Override
      public Trade parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Trade> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trade> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.semeniuk.lab3.protobuf.TradeOuterClass.Trade getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trade_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Trade_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/proto/Trade.proto\"Y\n\005Trade\022\016\n" +
      "\006stream\030\001 \001(\t\022\014\n\004coin\030\002 \001(\t\022\r\n\005price\030\003 \001" +
      "(\t\022\020\n\010quantity\030\004 \001(\t\022\021\n\ttradeTime\030\005 \001(\003B" +
      "-\n\032com.semeniuk.lab3.protobufB\017TradeOute" +
      "rClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Trade_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Trade_descriptor,
        new java.lang.String[] { "Stream", "Coin", "Price", "Quantity", "TradeTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
